version: "2.1"
services:
    api:
        container_name: api
        env_file: ./.env
        build:
          context: .
          dockerfile: ./Dockerfile
        image: docker/api
        restart: always
        ports:
          - "3000:3000"
        networks:
          daily-trends-network:
            aliases:
              - api

        volumes:
          - .:/app
    
networks:
  daily-trends-network:
    external:
      name: daily-trends-network